layout_spectrum: 0.01566238584928215
typography_spectrum: 0.39270024234429
author:
  name: Daniel Atwood
name: Spice
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.3888275537174195
  lightness: 0.8446808
  saturation: 0.2665104
  rhythmicContrast: 0
  brandColors:
    - '#170F0E'
    - '#290418'
    - '#505217'
    - '#FFD372'
    - '#FFF1AF'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e38d29d7-94e4-4d1f-8c36-72b0183de901.jpg
